### ISSUE TITLE
SuperNNova support cosmo_quantile norm

### ISSUE THREAD

**Issue by anaismoller** [Samreay/Pippin#10]
New norm available in SuperNNova cosmo_quantile. Please add this option when providing norm.

**Comment by anaismoller** [comment]
https://supernnova.readthedocs.io/en/latest/training/index.html#training-an-rnn-model-with-different-normalizations

**Comment by Samreay** [comment]
Added it in. Would you like this set as the default?

**Comment by anaismoller** [comment]
Probably. For cosmology it is needed when using redshift.
