### ISSUE TITLE
check argument of PATH_SNDATA_SIM

### ISSUE THREAD

**Issue by RickKessler** [Samreay/Pippin#12]
Pippin-Sim jobs on Cori(NERSC) failed because $SCRATCH_SIMDIR is not defined for

grep -R PATH_SNDATA *
data_files/combine.input:  PATH_SNDATA_SIM: $SCRATCH_SIMDIR

and the resulting blank argument causes all sim jobs to fail. Can you remove PATH_SNDATA_SIM if the argument is an undefined ENV ?

**Comment by Samreay** [comment]
Is there a reason we cant simply define a variable with that name that
points to the sim output?

**Comment by RickKessler** [comment]
Not sure what you are suggesting here ? Defining PATH_SNDATA_SIM in the pippin-input ?

**Comment by Samreay** [comment]
No I mean we should try and make common env variables that appear in top level files general, so they would be on both midway and NERSC, even if they point to different locations.
