### ISSUE TITLE
SNN cyclic and seed

### ISSUE THREAD

**Issue by anaismoller** [Samreay/Pippin#16]
enable in Pippin seed specification and no cyclic models in SNN

--seed is defualt set to zero but want to be able to specify it
--cyclic (True/False) as a true default in vanilla models but want to change that as well

**Comment by Samreay** [comment]
Give it a whirl now. Throw CYCLIC or SEED in OPTS and let me know if it works as intended

**Comment by Samreay** [comment]
Note Anais messaged me saying she now supports yml file input for SNN instead of massive command line lists. We should convert to that asap so we can clean up all the individual keywords in the task and just use the ConfigBaseExecutable task to automatically set properties.

**Comment by anaismoller** [comment]
Can we prioritise the yams implementation with Pippin or allow batch_size, num_layers, hidden_dim to be changed in Pippin? this will be need for the cosmo analysis.  @maria-vincenzi will need them!

**Comment by OmegaLambda1998** [comment]
On it! I'll get it done either today or tomorrow!

**Comment by OmegaLambda1998** [comment]
Added command line options. Will open a new issue for getting yaml inputs
