### ISSUE TITLE
Merge and Agg Tasks not consistently clobbering when rerun

### ISSUE THREAD

**Issue by djbrout** [Samreay/Pippin#18]
Sometimes when some lightcurve fitting has rerun for whatever reason, the merge and/or agg tasks will not get clobbered/rerun and then crash. ill try to dig up an example. it happens infrequently and im usually too impatient to submit an issue and wait for a response cause its easier just to clobber by hand

**Comment by djbrout** [comment]
Ah here is an example it just happened. I preserved the output directory because a simple fix is just to clobber it and force pippin to regenerate it...
`/scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS/5_MERGE/MERGE_PFITdatawithsys_DATAPS1keepforsam`

**Comment by Samreay** [comment]
This one might be tricky if we dont also have the original LOG file for the whole pipeline. Dillon, if this happens in the future, can you copy the main log into the preservation folder too?

Obviously first thing to do is check if this is an EXTERNAL task or not (EXTERNAL tasks get clobbered/regenerated differently). And then to check the hash generation, is it not updating when it should, why is it not updating. Ensure that the hash generation includes the hash from parent tasks (which it should, its hardcoded into `get_hash_from_string`). Check to see if the parent tasks hashes have changed or not.

**Comment by djbrout** [comment]
resolved
