### ISSUE TITLE
'inspect' not defined error in cosmomc.py

### ISSUE THREAD

**Issue by pmacias** [Samreay/Pippin#27]
Hello,

My pippin directory is 

$WFIRST_USERS/pmacias/pippin/config

and when I try to run

pippin.sh WFIRST_starterKit.yml

I get the following error:

File "/project2/rkessler/PRODUCTS/pippin/pippin/cosmomc.py", line 111, in __init__
    self.custom_slurm = options.get("CUSTOM_SLURM", os.path.dirname(inspect.stack()[0][1]) + "/external/cosmomc_slurm.job")
NameError: name 'inspect' is not defined

I see this part of the code has been recently edited and the code worked fine yesterday so I'm guessing this just popped up. Any help would be much appreciated!

Thanks,
Phil

**Comment by Samreay** [comment]
@djbrout pinging you over this as Im not sure if you get email notifications. Your commit (https://github.com/Samreay/Pippin/commit/b4e9ce0e0608aad4b10e798b8feab14acbd27833) broke the tests yesterday. Need that sweet import inspect at the top of the file

**Comment by djbrout** [comment]
Sorry! Not sure why this didnt crash on my side, but it is fixed now.
Need to pull the latest changes to the Pippin that is sitting on NERSC.

**Comment by djbrout** [comment]
is it here on NERSC?
/project/projectdirs/lsst/groups/SN/pippin
