### ISSUE TITLE
Emergency fix needed reading MERGE.LOG from SNANA-sim job

### ISSUE THREAD

**Issue by RickKessler** [Samreay/Pippin#29]
MERGE.LOG from sim job has extra column for NSPEC, which breaks pippin. In Pippin's snana_sim.py,  need to change
                        state, iver, version, ngen, nwrite, cpu = row
to
                        state, iver, version, ngen, nwrite, nspec, cpu = row

so that cpu is defined.

**Comment by OmegaLambda1998** [comment]
Do you have an example of the new MERGE.LOG somewhere?

**Comment by OmegaLambda1998** [comment]
This has been resolved via a645d4d
