### ISSUE TITLE
please add global CFG_FILE option under GLOBAL: key

### ISSUE THREAD

**Issue by RickKessler** [Samreay/Pippin#35]
Would be useful to allow
GLOBAL:
  CFG_FILE:  $PIPPIN_BASE/cfg_lsst_cori.yml

and not rely on $PIPPIN/cfg.yml since any machine-specific changes inside $PIPPIN will eventually get clobbered or forgotten.

**Comment by OmegaLambda1998** [comment]
```
GLOBAL:
  CFG_PATH: /your/path/here
```
