### ISSUE TITLE
UNITY and infinite probabilities

### ISSUE THREAD

**Issue by bap37** [Samreay/Pippin#4]
Hey! So, using pippin, and it's great and has made my life so much easier. 

But! I'm trying to aggregate a bunch of surveys together:

/project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BBC4D/BP_AS.yml

And in the process, I'm getting a bug where some of the surveys report infinite probability of being a Ia for certain SNe.

/project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BBC4D/LOG_FOR_SAM

Apparently, this is something Dillon has run into and knows how to fix if this error isn't clear enough.

Thank you!

**Comment by Samreay** [comment]
Ah how curious. I'll check it out in the morning!

**Comment by Samreay** [comment]
Ah just thought Id follow this up (after Anais raised an issue and I checked here for the first time in ages). The issue should have been fixed ages ago, have you had any problems recently?

**Comment by bap37** [comment]
It’s been so long since I had issues that I forgot that this was a problem I ever had!

On Sep 7, 2020, at 7:58 PM, Samuel Hinton <notifications@github.com<mailto:notifications@github.com>> wrote:



Ah just thought Id follow this up (after Anais raised an issue and I checked here for the first time in ages). The issue should have been fixed ages ago, have you had any problems recently?

**Comment by Samreay** [comment]
Let us hope it never rears its ugly head again
