### ISSUE TITLE
help sub-menus

### ISSUE THREAD

**Issue by RickKessler** [Samreay/Pippin#51]
e.g., 
pippin.sh -H FIT
pippin.sh -H SIM
pippin.sh -H BBC
pippin.sh -H CLASSIFY
pippin.sh -H COSMOMC

would provide help to explain input syntax for the particular block.

**Comment by OmegaLambda1998** [comment]
See #62 
New command line option -S (--syntax) N (taskname)
Specify either the task number (0, 1, 2, ...) or task name (DATAPREP, SIM, etc...) to see the documentation. Documentation is drawn from README.md so -S will always be up to date with the documentation!
