### ISSUE TITLE
MERGE task not found at launch

### ISSUE THREAD

**Issue by pmacias** [Samreay/Pippin#58]
Hi,

I'm trying to launch pippin and the job is dying at the config stage:

cd /project2/rkessler/SURVEYS/WFIRST/USERS/pmacias/dev/pippin
pippin.sh -c WFIRST_starterKit+ALT04.yml &

which yields 

"Unable to resolve merge WFIRSTfit_WFIRST_SIMDATA_G10 from list of merge_tasks. There are valid options: ['WFIRSTfit_WFIRST_BIASCOR_G10', 'FOUNDfit_FOUND_BIASCOR_G10']
Task failed config"

Rick and I checked the input file and can't find anything obvious, so any help would be much appreciated. Output (which is only the log file) is located here: 

/scratch/midway2/rkessler/PIPPIN_OUTPUT/WFIRST_STARTERKIT+ALT04

Thanks!
- Phil

**Comment by OmegaLambda1998** [comment]
Few issues in your input file.
1. You can't have duplicate LCFIT tasks, so having `WFIRSTfit_SIM` and `WFIRSTfit_BIAS` will fix up this issue. Make sure to update the biascor task with this as well.
2. The `CREATE_COV` task needs to mask a `BIASCOR` task so `MASK: BBC` is needed
3. `COSMOMC` should mask `CREATE_COV` so `MASK: WFIRST` is needed

See `/project2/rkessler/SURVEYS/DES/USERS/parmstrong/inputs/debug/pa_wfirst.yml` for a working example.
