### ISSUE TITLE
add new WFIT task

### ISSUE THREAD

**Issue by RickKessler** [Samreay/Pippin#70]
example inputs are on Midway under $SNANA_DEBUG/submit_batch_wfit
Pippin should auto-create a submit_batch input file of the form
    WFIT_DEBUG.INPUT
where each INPDIR is an output directory of create_covariance.
Launch task with
    submit_batch_jobs.sh WFIT_DEBUG.INPUT
Example pippin-input syntax is in pippin+wfit.yml

**Comment by OmegaLambda1998** [comment]
#73
