### ISSUE TITLE
Yaml anchoring no longer working

### ISSUE THREAD

**Issue by bap37** [Samreay/Pippin#8]
Since the new PIPPIN update, it seems like the ALIAS function doesn't work anymore. Specifically, 
/project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BBC_paper_2/PS1_usable/BP-PS1.yml

PIPPIN is no longer overwriting the HOSTLIB file specified in the above file. I think this is probably a syntax issue, but I'm not sure where I've gone wrong, exactly.

**Comment by Samreay** [comment]
Will loop Rick into this, the outputs from Pippin all look correct, so the breakdown is between the input file and SNANA reading it

**Comment by Samreay** [comment]
Rick figured out the issue, closing :)
